# Generated by Django 4.1.2 on 2023-01-13 06:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0005_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='liked_by',
            field=models.ManyToManyField(related_name='like', to=settings.AUTH_USER_MODEL),
        ),
    ]
